//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.6.3
//     from Assets/Scripts/Controls/InputMaster.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputMaster: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputMaster()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputMaster"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""373ed177-2e69-404b-9d0a-30e7fa2c3ca0"",
            ""actions"": [
                {
                    ""name"": ""Look"",
                    ""type"": ""Value"",
                    ""id"": ""a7500ccf-5b62-472d-b160-5f6675a75a33"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""5a920127-9940-4ed9-9080-1b485c35ebc7"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""bd027014-a0ce-4ac7-af33-5e5297216bbd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ToggleLegs"",
                    ""type"": ""Button"",
                    ""id"": ""b72784af-7822-459a-973c-92d5fc8a5465"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ToggleRightArm"",
                    ""type"": ""Button"",
                    ""id"": ""94b44058-db90-4414-a6cf-e0eda4dbd0de"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ToggleBody"",
                    ""type"": ""Button"",
                    ""id"": ""dcc80d66-cb24-4f53-aa39-064692717747"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ToggleLeftArm"",
                    ""type"": ""Button"",
                    ""id"": ""1a5616d6-2e77-4bc0-a3e2-bd7278dcd036"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Shoot"",
                    ""type"": ""Button"",
                    ""id"": ""3116fe6c-a117-4ae7-9a34-e0846089fec6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ToggleDevMode"",
                    ""type"": ""Button"",
                    ""id"": ""8c8eff0e-c459-4b24-ad79-82f099030016"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""InstantiateEnemy"",
                    ""type"": ""Button"",
                    ""id"": ""553ad1fc-0ad9-4d7b-a7e4-f8861f44f8d3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ToggleEnemy"",
                    ""type"": ""Button"",
                    ""id"": ""355b279a-c29e-4ee3-867c-a6b4207d3ebd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Pause"",
                    ""type"": ""Button"",
                    ""id"": ""d1927c65-8801-436c-a7a3-46d46d9cc435"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ToggleBackRightArm"",
                    ""type"": ""Button"",
                    ""id"": ""6b6ab023-5e92-45d8-b78a-12cb465cbfba"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""cc6b6de8-8a34-484c-84ba-0ca1f2efd7dc"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b2df8ad8-b0ca-4391-959d-789591467c30"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""WASD"",
                    ""id"": ""0defeff1-e836-4e15-95ff-56caf872d092"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""7756357b-da51-44ff-8e4d-578374dc3ea4"",
                    ""path"": ""<Keyboard>/#(W)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""640b3612-6a0c-4f50-9a64-022328e5c646"",
                    ""path"": ""<Keyboard>/#(S)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""1088106b-6035-49fa-8cc8-d27363cd5946"",
                    ""path"": ""<Keyboard>/#(A)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""a94f6698-31af-42b6-b0f0-a5bdb28758bc"",
                    ""path"": ""<Keyboard>/#(D)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""0479e7f3-c893-4b68-8923-0c0fdfaca53b"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6530d4cc-ff03-41ff-bf46-ad6123fdf3eb"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ef90a0bf-732c-47db-abf3-e80207333dc3"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e5bfeab2-3baf-4260-93ef-d07b7c2af239"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""70046ffa-cf87-460e-a27f-cd5b06308cca"",
                    ""path"": ""<Keyboard>/leftCtrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleLegs"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e0cd0882-5777-4915-b7de-9733c22ea727"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleRightArm"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2cc30647-ee9e-4afb-8c42-fa386938bef5"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleBody"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2d524142-73e9-4ea9-9afc-4b690cd7e54b"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleBody"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3fc18601-6e21-47c8-a089-2d04bee95781"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleBody"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7c2e4fff-6643-4c8c-bbbb-cb93c1d81909"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleLeftArm"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d6fa5833-cf70-4e63-a659-49ea4e646f26"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleLeftArm"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7ffeb4e8-0eab-4125-9178-d6e26653597c"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleLeftArm"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a8506991-5428-42af-b438-8f496a0185d0"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleRightArm"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fda1ad9e-2dc8-4297-aaa5-c7ba552afb2c"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleRightArm"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""90b35a4d-5df5-4264-bae3-84e0cb6450ba"",
                    ""path"": ""<Mouse>/forwardButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleRightArm"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""18ce514a-7863-4339-bb93-6a7b190bb98b"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleLegs"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""94493a6c-725e-474a-aeb5-4a41e2c23cdc"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleLegs"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e36d613b-eb8a-4d38-97cf-f0fa67691606"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Shoot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0e93204f-8c79-41d1-950a-7eb190045197"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Shoot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""34321535-eab7-4515-ab58-db8cd786f6a7"",
                    ""path"": ""<Keyboard>/backquote"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleDevMode"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7541342c-d53f-415c-b5a4-540d6a13acc9"",
                    ""path"": ""<Gamepad>/select"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleDevMode"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f238057b-42ca-4bcc-a663-ea307b13ca19"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""InstantiateEnemy"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""71ff88e0-d496-4734-abcf-60f5ba9b7238"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""InstantiateEnemy"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5d74d4fd-d87e-40f8-b48d-6393860c06fc"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleEnemy"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""49470dad-9670-46ae-8b4f-0f8b82a5fee2"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleEnemy"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e1c30535-c6c4-4a6c-a05f-ffac2ccd0767"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b8a334f1-1c72-4034-8cb6-6e338b012f6b"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d94d66ca-ffe5-48b4-b292-79e702ada748"",
                    ""path"": ""<Mouse>/backButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleBackRightArm"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_Look = m_Player.FindAction("Look", throwIfNotFound: true);
        m_Player_Move = m_Player.FindAction("Move", throwIfNotFound: true);
        m_Player_Jump = m_Player.FindAction("Jump", throwIfNotFound: true);
        m_Player_ToggleLegs = m_Player.FindAction("ToggleLegs", throwIfNotFound: true);
        m_Player_ToggleRightArm = m_Player.FindAction("ToggleRightArm", throwIfNotFound: true);
        m_Player_ToggleBody = m_Player.FindAction("ToggleBody", throwIfNotFound: true);
        m_Player_ToggleLeftArm = m_Player.FindAction("ToggleLeftArm", throwIfNotFound: true);
        m_Player_Shoot = m_Player.FindAction("Shoot", throwIfNotFound: true);
        m_Player_ToggleDevMode = m_Player.FindAction("ToggleDevMode", throwIfNotFound: true);
        m_Player_InstantiateEnemy = m_Player.FindAction("InstantiateEnemy", throwIfNotFound: true);
        m_Player_ToggleEnemy = m_Player.FindAction("ToggleEnemy", throwIfNotFound: true);
        m_Player_Pause = m_Player.FindAction("Pause", throwIfNotFound: true);
        m_Player_ToggleBackRightArm = m_Player.FindAction("ToggleBackRightArm", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private List<IPlayerActions> m_PlayerActionsCallbackInterfaces = new List<IPlayerActions>();
    private readonly InputAction m_Player_Look;
    private readonly InputAction m_Player_Move;
    private readonly InputAction m_Player_Jump;
    private readonly InputAction m_Player_ToggleLegs;
    private readonly InputAction m_Player_ToggleRightArm;
    private readonly InputAction m_Player_ToggleBody;
    private readonly InputAction m_Player_ToggleLeftArm;
    private readonly InputAction m_Player_Shoot;
    private readonly InputAction m_Player_ToggleDevMode;
    private readonly InputAction m_Player_InstantiateEnemy;
    private readonly InputAction m_Player_ToggleEnemy;
    private readonly InputAction m_Player_Pause;
    private readonly InputAction m_Player_ToggleBackRightArm;
    public struct PlayerActions
    {
        private @InputMaster m_Wrapper;
        public PlayerActions(@InputMaster wrapper) { m_Wrapper = wrapper; }
        public InputAction @Look => m_Wrapper.m_Player_Look;
        public InputAction @Move => m_Wrapper.m_Player_Move;
        public InputAction @Jump => m_Wrapper.m_Player_Jump;
        public InputAction @ToggleLegs => m_Wrapper.m_Player_ToggleLegs;
        public InputAction @ToggleRightArm => m_Wrapper.m_Player_ToggleRightArm;
        public InputAction @ToggleBody => m_Wrapper.m_Player_ToggleBody;
        public InputAction @ToggleLeftArm => m_Wrapper.m_Player_ToggleLeftArm;
        public InputAction @Shoot => m_Wrapper.m_Player_Shoot;
        public InputAction @ToggleDevMode => m_Wrapper.m_Player_ToggleDevMode;
        public InputAction @InstantiateEnemy => m_Wrapper.m_Player_InstantiateEnemy;
        public InputAction @ToggleEnemy => m_Wrapper.m_Player_ToggleEnemy;
        public InputAction @Pause => m_Wrapper.m_Player_Pause;
        public InputAction @ToggleBackRightArm => m_Wrapper.m_Player_ToggleBackRightArm;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Add(instance);
            @Look.started += instance.OnLook;
            @Look.performed += instance.OnLook;
            @Look.canceled += instance.OnLook;
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
            @Jump.started += instance.OnJump;
            @Jump.performed += instance.OnJump;
            @Jump.canceled += instance.OnJump;
            @ToggleLegs.started += instance.OnToggleLegs;
            @ToggleLegs.performed += instance.OnToggleLegs;
            @ToggleLegs.canceled += instance.OnToggleLegs;
            @ToggleRightArm.started += instance.OnToggleRightArm;
            @ToggleRightArm.performed += instance.OnToggleRightArm;
            @ToggleRightArm.canceled += instance.OnToggleRightArm;
            @ToggleBody.started += instance.OnToggleBody;
            @ToggleBody.performed += instance.OnToggleBody;
            @ToggleBody.canceled += instance.OnToggleBody;
            @ToggleLeftArm.started += instance.OnToggleLeftArm;
            @ToggleLeftArm.performed += instance.OnToggleLeftArm;
            @ToggleLeftArm.canceled += instance.OnToggleLeftArm;
            @Shoot.started += instance.OnShoot;
            @Shoot.performed += instance.OnShoot;
            @Shoot.canceled += instance.OnShoot;
            @ToggleDevMode.started += instance.OnToggleDevMode;
            @ToggleDevMode.performed += instance.OnToggleDevMode;
            @ToggleDevMode.canceled += instance.OnToggleDevMode;
            @InstantiateEnemy.started += instance.OnInstantiateEnemy;
            @InstantiateEnemy.performed += instance.OnInstantiateEnemy;
            @InstantiateEnemy.canceled += instance.OnInstantiateEnemy;
            @ToggleEnemy.started += instance.OnToggleEnemy;
            @ToggleEnemy.performed += instance.OnToggleEnemy;
            @ToggleEnemy.canceled += instance.OnToggleEnemy;
            @Pause.started += instance.OnPause;
            @Pause.performed += instance.OnPause;
            @Pause.canceled += instance.OnPause;
            @ToggleBackRightArm.started += instance.OnToggleBackRightArm;
            @ToggleBackRightArm.performed += instance.OnToggleBackRightArm;
            @ToggleBackRightArm.canceled += instance.OnToggleBackRightArm;
        }

        private void UnregisterCallbacks(IPlayerActions instance)
        {
            @Look.started -= instance.OnLook;
            @Look.performed -= instance.OnLook;
            @Look.canceled -= instance.OnLook;
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
            @Jump.started -= instance.OnJump;
            @Jump.performed -= instance.OnJump;
            @Jump.canceled -= instance.OnJump;
            @ToggleLegs.started -= instance.OnToggleLegs;
            @ToggleLegs.performed -= instance.OnToggleLegs;
            @ToggleLegs.canceled -= instance.OnToggleLegs;
            @ToggleRightArm.started -= instance.OnToggleRightArm;
            @ToggleRightArm.performed -= instance.OnToggleRightArm;
            @ToggleRightArm.canceled -= instance.OnToggleRightArm;
            @ToggleBody.started -= instance.OnToggleBody;
            @ToggleBody.performed -= instance.OnToggleBody;
            @ToggleBody.canceled -= instance.OnToggleBody;
            @ToggleLeftArm.started -= instance.OnToggleLeftArm;
            @ToggleLeftArm.performed -= instance.OnToggleLeftArm;
            @ToggleLeftArm.canceled -= instance.OnToggleLeftArm;
            @Shoot.started -= instance.OnShoot;
            @Shoot.performed -= instance.OnShoot;
            @Shoot.canceled -= instance.OnShoot;
            @ToggleDevMode.started -= instance.OnToggleDevMode;
            @ToggleDevMode.performed -= instance.OnToggleDevMode;
            @ToggleDevMode.canceled -= instance.OnToggleDevMode;
            @InstantiateEnemy.started -= instance.OnInstantiateEnemy;
            @InstantiateEnemy.performed -= instance.OnInstantiateEnemy;
            @InstantiateEnemy.canceled -= instance.OnInstantiateEnemy;
            @ToggleEnemy.started -= instance.OnToggleEnemy;
            @ToggleEnemy.performed -= instance.OnToggleEnemy;
            @ToggleEnemy.canceled -= instance.OnToggleEnemy;
            @Pause.started -= instance.OnPause;
            @Pause.performed -= instance.OnPause;
            @Pause.canceled -= instance.OnPause;
            @ToggleBackRightArm.started -= instance.OnToggleBackRightArm;
            @ToggleBackRightArm.performed -= instance.OnToggleBackRightArm;
            @ToggleBackRightArm.canceled -= instance.OnToggleBackRightArm;
        }

        public void RemoveCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerActions @Player => new PlayerActions(this);
    public interface IPlayerActions
    {
        void OnLook(InputAction.CallbackContext context);
        void OnMove(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnToggleLegs(InputAction.CallbackContext context);
        void OnToggleRightArm(InputAction.CallbackContext context);
        void OnToggleBody(InputAction.CallbackContext context);
        void OnToggleLeftArm(InputAction.CallbackContext context);
        void OnShoot(InputAction.CallbackContext context);
        void OnToggleDevMode(InputAction.CallbackContext context);
        void OnInstantiateEnemy(InputAction.CallbackContext context);
        void OnToggleEnemy(InputAction.CallbackContext context);
        void OnPause(InputAction.CallbackContext context);
        void OnToggleBackRightArm(InputAction.CallbackContext context);
    }
}
